[package]
name = "hello"
version = "0.1.0"
authors = ["members007 <ikedayuu@keio.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
